[[redirects]]
  from = "/__/auth/*"
  to = "https://neural-cortex-app-2026.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
